### PR TITLE
Update LCA.py

### PR DESCRIPTION
**Pull request by avg16**
I think gumbel_softmax is not performing up to the mark on some datasets, I re evaluated it

### CODE REVIEW

**Comment by Fediory** [comment]
Please give me some details about performance on gumbel_softmax

**Comment by avg16** [comment]
> Please give me some details about performance on gumbel_softmax

not performing up to the mark on Sony total dark, SICE

**Comment by Fediory** [comment]
How much have the PSNR and SSIM metrics dropped, respectively?

**Comment by avg16** [comment]
> How much have the PSNR and SSIM metrics dropped, respectively?

something less then 22

**Comment by Fediory** [comment]
What about the LOL related datasets?

**Pull request merged**
